export const products = [
    // Chairs
    {
      id: 1,
      name: "Comfortable Chair",
      category: "Chair",
      price: 99,
      imageUrl: "https://i.ibb.co.com/Q7CKj8V7/chair-1.png",
      rating: 5,
    },
    {
      id: 2,
      name: "Ergonomic Chair",
      category: "Chair",
      price: 129,
      imageUrl: "https://i.ibb.co.com/fVMfG7TT/chair-2.png",
      rating: 4,
    },
    {
      id: 3,
      name: "Stylish Armchair",
      category: "Chair",
      price: 149,
      imageUrl: "https://i.ibb.co.com/n88Tp2Nq/chair-3.png",
      rating: 3,
    },
    {
      id: 4,
      name: "Leather Recliner",
      category: "Chair",
      price: 199,
      imageUrl: "https://i.ibb.co.com/N6NPJ38H/chair-4.png",
      rating: 4,
    },
    {
      id: 5,
      name: "Minimalist Chair",
      category: "Chair",
      price: 89,
      imageUrl: "https://i.ibb.co.com/TBmDpJnC/chair-5.png",
      rating: 4.5,
    },
    
  
    // Beds
    {
      id: 6,
      name: "King Size Bed",
      category: "Beds",
      price: 299,
      imageUrl: "https://i.ibb.co.com/YBfD50Nr/beds-1.png",
      rating: 5,
    },
    {
      id: 7,
      name: "Queen Size Bed",
      category: "Beds",
      price: 249,
      imageUrl: "https://i.ibb.co.com/LdsjDkSN/beds-2.png",
      rating: 5,
    },
    {
      id: 8,
      name: "Modern Bed Frame",
      category: "Beds",
      price: 399,
      imageUrl: "https://i.ibb.co.com/j9K0wyxk/beds-3.png",
      rating: 3,
    },
    {
      id: 9,
      name: "Platform Bed",
      category: "Beds",
      price: 349,
      imageUrl: "https://i.ibb.co.com/Zpr18qHK/beds-4.png",
      rating: 2,
    },
    {
      id: 10,
      name: "Sleigh Bed",
      category: "Beds",
      price: 459,
      imageUrl: "https://i.ibb.co.com/bjgQWyDb/beds-5.png",
      rating: 5,
    },
  
    // Sofas
    {
      id: 11,
      name: "Luxury Sofa",
      category: "Sofa",
      price: 499,
      imageUrl: "https://i.ibb.co.com/spSNd2Gz/sofa-1.png",
      rating: 4,
    },
    {
      id: 12,
      name: "Compact Sofa",
      category: "Sofa",
      price: 399,
      imageUrl: "https://i.ibb.co.com/3mc9X09Y/sofa-2.png",
      rating: 5,
    },
    {
      id: 13,
      name: "L-shaped Sofa",
      category: "Sofa",
      price: 699,
      imageUrl: "https://i.ibb.co.com/1GcMy6xk/sofa-3.png",
      rating: 4,
    },
    {
      id: 14,
      name: "Sofa with Chaise",
      category: "Sofa",
      price: 549,
      imageUrl: "https://i.ibb.co.com/KzG929b6/sofa-4.png",
      rating: 5,
    },
    {
      id: 15,
      name: "Sectional Sofa",
      category: "Sofa",
      price: 799,
      imageUrl: "https://i.ibb.co.com/nN0QrxPp/sofa-5.png",
      rating: 3.6,
    },
  
    // Lamps
    {
      id: 16,
      name: "Modern Lamp",
      category: "Lamp",
      price: 49,
      imageUrl: "https://i.ibb.co.com/qFFgGd2r/lamp-1.png",
      rating: 5,
    },
    {
      id: 17,
      name: "Classic Lamp",
      category: "Lamp",
      price: 59,
      imageUrl: "https://i.ibb.co.com/GQX5zBBG/lamp-2.png",
      rating: 4,
    },
    {
      id: 18,
      name: "Wooden Table Lamp",
      category: "Lamp",
      price: 69,
      imageUrl: "https://i.ibb.co.com/ZqTHj8d/lamp-3.png",
      rating: 3,
    },
    {
      id: 19,
      name: "Industrial Floor Lamp",
      category: "Lamp",
      price: 89,
      imageUrl: "https://i.ibb.co.com/c9Mh0wv/lamp-4.png",
      rating: 5,
    },
    {
      id: 20,
      name: "Vintage Desk Lamp",
      category: "Lamp",
      price: 79,
      imageUrl: "https://i.ibb.co.com/MkYsq037/lamp-5.png",
      rating: 4,
    },
  ];